const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const assert = require('node:assert/strict');
const code = ts.transpileModule(fs.readFileSync('src/lib/licence-csv.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const context = vm.createContext({ exports: {}, Intl, Date, AbortSignal, fetch: async () => { throw Error('offline'); } });
vm.runInContext(code, context);
const { checkCsvLicence: check, parseLicenceCsv: parse } = context.exports;
const header = 'AUTH CODE,Org Code,User Name,email,Validity Upto,Validation Status';
const row = 'K1,DEMO,"User, One",user@example.com,03-12-2027,Active';
const sheet = header + '\r\n' + row;
assert.equal(check(sheet, ' k1 ', ' USER@example.com ', '2027-12-03').validUntil, '2027-12-03');
assert.throws(() => check(sheet, 'K1', 'other@example.com', '2026-10-03'), /assigned/);
assert.throws(() => check(sheet.replace(',Active', ',Inactive'), 'K1', 'user@example.com', '2026-10-03'), /Active/);
assert.throws(() => check(sheet.replace(',Active', ','), 'K1', 'user@example.com', '2026-10-03'), /Active/);
assert.throws(() => check(sheet, 'K1', 'user@example.com', '2027-12-04'), /expired/);
assert.throws(() => check(sheet.replace('03-12-2027', '31-11-2027'), 'K1', 'user@example.com', '2026-10-03'), /invalid/);
assert.throws(() => check(sheet + '\n' + row, 'K1', 'user@example.com', '2026-10-03'), /assigned/);
assert.throws(() => check(sheet.replace(',email,', ',missing,'), 'K1', 'user@example.com', '2026-10-03'), /column/);
assert.equal(parse('a,b\n"line\nsecond","quote ""here"""')[1][0], 'line\nsecond');
assert.equal(parse('\uFEFFa,b\n1,2')[0][0], 'a');
context.exports.readCsvLicence('K1', 'user@example.com').then(() => { throw Error('Offline check unexpectedly passed'); }, () => console.log('CSV licence tests: exact status, email, expiry, duplicate keys, quoting and offline rejection pass'));
