import { rest } from './rest-rows.mjs';

export function register(add, q) {
  const rows = [
    ['intermediate', 'Verbs (deeper forms)', 'INT-01', 'Finite and non-finite verbs', 'A finite verb shows tense and agrees with a subject. A non-finite form does not stand as the main verb alone.', 'She leaves at 7, hoping the bus is there.', 'Leaves is finite. Hoping is non-finite.', 'She hoping the bus is there.', 'Hoping cannot be the only verb.', [['The finite verb in “She leaves at 7” is…', 'leaves', 'at', 'she', '7', 0, 'Leaves shows present tense and matches she.'], ['Hoping in “leaves, hoping” is…', 'non-finite', 'the only verb the sentence needs', 'a noun', 'an article', 0, 'It does not carry the tense by itself.'], ['Which line has a finite verb?', 'They waited.', 'Waiting at the stop.', 'To wait there.', 'The waiting students only as a phrase.', 0, 'Waited is a finished finite verb.'], ['A non-finite form often looks like…', 'to leave, leaving, or left as a participle', 'she leaves', 'a question mark', 'a capital', 0, 'Infinitives and participles are non-finite.']]],
    ['intermediate', 'Verbs (deeper forms)', 'INT-02', 'Infinitives, gerunds and participles', 'To leave is an infinitive. Leaving can be a gerund. Left or leaving can be a participle.', 'Leaving early means we catch the bus. She wants to leave.', 'Leaving is a gerund subject. To leave is an infinitive.', 'Leave early mean we catch the bus.', 'The -ing form is missing, so the subject is not a noun-like verb.', [['“To leave” is an…', 'infinitive', 'gerund', 'article', 'plural noun', 0, 'To plus the base verb is the infinitive.'], ['“Leaving early is hard” uses leaving as a…', 'gerund', 'finite past verb', 'preposition', 'pronoun', 0, 'The -ing form is the subject, so it works as a noun.'], ['A participle can describe a noun, as in…', 'the students waiting outside', 'to the outside', 'wait they', 'a wait', 0, 'Waiting describes students.'], ['Which pair matches the names?', 'to go / going', 'goed / goest', 'a go / an go', 'goes / a goes', 0, 'To go is the infinitive. Going can be the gerund.']]],
    ['intermediate', 'Verbs (deeper forms)', 'INT-03', 'The 12 tenses', 'English builds twelve tense-aspect forms from past, present, and future, each simple, continuous, perfect, or perfect continuous.', 'I text, I am texting, I have texted, I have been texting.', 'Those four are the present group.', 'I am texted now for a habit.', 'The names of the forms are mixed up.', [['A habit such as “I take the bus” is…', 'present simple', 'present perfect continuous', 'past perfect', 'future perfect', 0, 'Repeated facts use the present simple.'], ['“I am texting” is…', 'present continuous', 'past simple', 'future perfect', 'present perfect only', 0, 'Am plus -ing is present continuous.'], ['“She had left” is…', 'past perfect', 'present simple', 'future continuous', 'a noun', 0, 'Had plus the past participle is past perfect.'], ['How many tense-aspect combinations are in the usual set?', '12', '3', '2', '20', 0, 'Three times and four aspects make twelve.']]],
    ['intermediate', 'Verbs (deeper forms)', 'INT-04', 'Sequence of tenses', 'The tense of a later verb should fit the tense of the verb it follows.', 'She said she was tired.', 'Said is past, so was matches that past point of view.', 'She said she is tired yesterday in reported speech.', 'The second verb does not follow the past reporting verb.', [['After “She said,” the usual match is…', 'she was tired', 'she is tired yesterday', 'she tired', 'she being tired as the only verb', 0, 'A past reporting verb pulls the next verb into the past.'], ['“I know she leaves at 7” keeps the present because…', 'know is present', 'know is past', 'leaves is a noun', '7 is plural', 0, 'A present main verb can keep a present following verb.'], ['Which sequence fits?', 'He realised he had missed it.', 'He realised he misses it yesterday.', 'He realise he had miss.', 'Had he realised miss.', 0, 'Realised is past, and had missed is earlier than that.'], ['Sequence of tenses is about…', 'making the times fit together', 'adding capital letters', 'counting nouns', 'spelling -ed', 0, 'The times in one sentence should agree.']]],
    ['intermediate', 'Verbs (deeper forms)', 'INT-05', 'Modal verbs', 'Modals such as can, could, may, might, must, should, and will add meaning and are followed by the base verb.', 'You should text her. I can hear the bus.', 'Should and can take the base form, with no to.', 'You should to text her.', 'To does not sit between a modal and the verb.', [['After can, use…', 'the base verb', 'to plus verb', 'the past participle always', 'an -ing form always', 0, 'Can hear, not can to hear.'], ['Should often means…', 'advice', 'a finished past fact by itself', 'a plural noun', 'ownership', 0, 'You should text her is advice.'], ['Must can mean…', 'obligation', 'a question mark', 'an article', 'a spelling rule', 0, 'You must show your pass is a strong obligation.'], ['Which line is formed correctly?', 'She might be late.', 'She might to be late.', 'She might being late.', 'She mights be late.', 0, 'Might is followed by the base form be.']]],
    ['intermediate', 'Verbs (deeper forms)', 'INT-06', 'Phrasal verbs', 'A phrasal verb is a verb plus a particle whose meaning is often different from the verb alone.', 'Look up the word. We put off the quiz.', 'Look up means search. Put off means postpone.', 'Look the word to the sky only, when you mean search.', 'The particle changes the meaning.', [['“Put off the quiz” means…', 'postpone it', 'place it on a table only', 'cancel the particle', 'spell it', 0, 'Put off is a phrasal verb meaning postpone.'], ['“Look up a word” means…', 'search for it', 'stare at the ceiling only', 'delete it', 'capitalise it', 0, 'The particle up makes it mean search.'], ['Which is a phrasal verb?', 'give up', 'give a gift only', 'gift up', 'a give', 0, 'Give up means quit.'], ['The little word in a phrasal verb is called a…', 'particle', 'article', 'subject', 'capital', 0, 'Up, off, and out are particles here.']]],
  ];
  for (const row of rows.concat(rest)) add(row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9].map((item) => q(...item)));
}
