function R(level, section, id, title, summary, good, goodNote, weak, weakNote, questions) {
  return [level, section, id, title, summary, good, goodNote, weak, weakNote, questions];
}
const Q = (prompt, a, b, c, d, index, why) => [prompt, a, b, c, d, index, why];

export const rest = [
  R('intermediate', 'Sentence Construction', 'INT-07', 'Simple, compound and complex sentences',
    'A simple sentence has one clause. A compound sentence joins two equals. A complex sentence has a main clause and a dependent one.',
    'The bus left, and we walked. When the bus left, we walked.',
    'And joins equals. When makes the first clause dependent.',
    'The bus left we walked.',
    'Two clauses are stuck together with no join.',
    [Q('“The bus left” is…', 'simple', 'compound', 'a fragment with when', 'two sentences', 0, 'It has one subject and one verb.'), Q('And in “The bus left, and we walked” makes the sentence…', 'compound', 'complex', 'a phrase only', 'a question', 0, 'And joins two independent clauses.'), Q('“When the bus left, we walked” is…', 'complex', 'simple', 'a single noun', 'a spelling rule', 0, 'When introduces a dependent clause.'), Q('Which join is missing?', 'The bus left we walked.', 'The bus left, so we walked.', 'When the bus left, we walked.', 'We walked.', 0, 'Those two clauses need punctuation or a joining word.')]),
  R('intermediate', 'Sentence Construction', 'INT-08', 'Independent and dependent clauses',
    'An independent clause can stand alone. A dependent clause cannot.',
    'We walked because the bus left.',
    'We walked can stand alone. Because the bus left cannot.',
    'Because the bus left.',
    'The dependent clause is pretending to be a sentence.',
    [Q('Which clause can stand alone?', 'We walked.', 'Because the bus left.', 'When Maya texted.', 'If the bus is late.', 0, 'We walked is independent.'), Q('Because the bus left is…', 'dependent', 'a full sentence', 'a noun only', 'an article', 0, 'It needs a main clause.'), Q('A dependent clause often starts with a word such as…', 'because, when, or if', 'and only', 'a capital I', 'a full stop', 0, 'Those words make the clause lean on another one.'), Q('Which line is complete?', 'We walked because the bus left.', 'Because the bus left.', 'When Maya.', 'If late.', 0, 'The independent clause is attached.')]),
  R('intermediate', 'Sentence Construction', 'INT-09', 'Noun, adjective and adverb clauses',
    'A clause can do the job of a noun, an adjective, or an adverb.',
    'I know that she left. The bus that we missed is gone. We left when it started.',
    'That she left is a noun clause. That we missed describes the bus. When it started tells when.',
    'I know that. The bus that. We left when.',
    'The clauses are cut off.',
    [Q('“I know that she left” — that she left works as a…', 'noun clause', 'adjective describing know', 'capital letter', 'plural', 0, 'It is the thing you know.'), Q('“The bus that we missed” — the clause describes…', 'the bus', 'the verb only', 'a preposition', 'a comma', 0, 'It works like an adjective.'), Q('“We left when it started” tells…', 'when we left', 'who owns the bus', 'a spelling', 'a name', 0, 'When it started is an adverb clause.'), Q('Which is a noun clause?', 'what she said', 'the loud bus', 'quickly', 'on Monday', 0, 'What she said can be the object of a verb.')]),
  R('intermediate', 'Sentence Construction', 'INT-10', 'Relative clauses and relative pronouns',
    'Who, which, and that introduce a clause that describes a noun.',
    'The friend who lent me the charger is waiting.',
    'Who lent me the charger tells us which friend.',
    'The friend which lent me the charger.',
    'Which is for things. A friend takes who or that.',
    [Q('A person is usually followed by…', 'who', 'which', 'where for a person', 'at', 0, 'Who refers to people.'), Q('A thing is often followed by…', 'which or that', 'who', 'she', 'a capital', 0, 'Which and that refer to things.'), Q('“The seat that we saved” describes…', 'the seat', 'saved as a noun', 'we only', 'a tense', 0, 'The relative clause identifies the seat.'), Q('Which line fits a person?', 'The coach who waited is new.', 'The coach which waited is new.', 'The coach where waited.', 'Coach who the.', 0, 'Who agrees with a person.')]),
  R('intermediate', 'Sentence Construction', 'INT-11', 'Coordinating and subordinating conjunctions',
    'And, but, and or join equals. Because, although, and if start a dependent clause.',
    'We ran, but the bus left because we were late.',
    'But joins two main ideas. Because starts the reason.',
    'We ran but, the bus left because.',
    'The joining words are stranded.',
    [Q('But is a…', 'coordinating conjunction', 'subordinating conjunction', 'pronoun', 'tense', 0, 'It joins two clauses of the same rank.'), Q('Because is a…', 'subordinating conjunction', 'coordinating conjunction', 'noun', 'article', 0, 'It makes the following clause dependent.'), Q('Which word can replace and between equals?', 'or', 'although', 'because', 'when', 0, 'Or coordinates. Although subordinates.'), Q('Choose the natural join.', 'She stayed although she was tired.', 'She stayed and although tired was.', 'Although she stayed, because.', 'But she stayed because,', 0, 'Although introduces the contrast and the main clause is complete.')]),
  R('intermediate', 'Sentence Construction', 'INT-12', 'Conditional sentences',
    'If sets a condition. The tense shows whether the result is real, unlikely, or imagined.',
    'If the bus is late, I walk. If I had set an alarm, I would not be late now.',
    'The first is a real habit. The second is an unreal past with a present result.',
    'If the bus will late, I walked always.',
    'The verb forms do not match a conditional pattern.',
    [Q('“If you heat water, it boils” is a…', 'real, always-true conditional', 'past unreal wish', 'command', 'plural noun', 0, 'Both verbs are present because the result always happens.'), Q('“If I were you, I would leave” imagines…', 'something unreal now', 'a scientific fact', 'a plural', 'an article', 0, 'Were and would mark an unreal present.'), Q('A past mistake with a present result can be…', 'If I had left earlier, I would be there now.', 'If I leave yesterday, I am there.', 'If I had, leave.', 'Had if leave now.', 0, 'Had left is past. Would be is present.'), Q('If is the word that…', 'sets the condition', 'always means and', 'makes a noun plural', 'replaces a subject', 0, 'The if-clause is the condition.')]),
  R('intermediate', 'Sentence Construction', 'INT-13', 'Question formation and question tags',
    'Most questions move a helping verb before the subject. A tag asks for agreement.',
    'Did she leave? She left, didn’t she?',
    'Did opens the question. The tag didn’t she? checks the positive statement.',
    'She did leave? She left, did she? when you expect agreement with a positive.',
    'The helping verb and the tag do not match the usual pattern.',
    [Q('A yes/no question often starts with…', 'a helping verb', 'the object', 'an adjective', 'a full stop', 0, 'Did she leave? starts with did.'), Q('A positive statement takes a…', 'negative tag', 'positive tag when you simply expect yes', 'noun tag', 'no tag ever', 0, 'She left, didn’t she?'), Q('“You can hear it, ___?”', 'can’t you', 'can you as the usual check', 'hear you', 'it you', 0, 'The positive can takes the negative tag.'), Q('Which question is formed in the usual way?', 'Where did they go?', 'Where they did go?', 'Where went they?', 'Did where they go?', 0, 'Did comes before the subject.')]),
  R('intermediate', 'Sentence Construction', 'INT-14', 'Negative sentences',
    'A negative sentence uses not, usually with a helping verb, and avoids a second negative.',
    'She does not have a pass. I can hear nothing.',
    'Does not is one negative. Nothing is the single negative in the second sentence.',
    'She does not have no pass.',
    'Not and no cancel or clash.',
    [Q('The natural negative of “She has a pass” is…', 'She does not have a pass.', 'She does not have no pass.', 'She not has a pass.', 'She have not pass.', 0, 'One negative is enough, and does supports not.'), Q('“I can’t find it” means…', 'I am unable to find it', 'I can find it', 'I found it', 'find is a noun', 0, 'Can’t is the negative of can.'), Q('Double negatives such as “don’t have no” …', 'are avoided in standard sentences', 'are required', 'replace the subject', 'make a plural', 0, 'One negative carries the meaning.'), Q('Not usually follows…', 'a helping verb', 'the object with no helper', 'a comma only', 'a capital', 0, 'Does not, is not, cannot.')]),
  R('intermediate', 'Sentence Construction', 'INT-15', 'Sentence transformation',
    'The same meaning can be reshaped: active to passive, statement to question, or two sentences into one.',
    'Maya sent the file. The file was sent by Maya.',
    'The meaning stays. The focus moves from Maya to the file.',
    'Maya sent the file. The file sent Maya.',
    'The second line changes who did the action.',
    [Q('“Maya sent the file” becomes…', 'The file was sent by Maya.', 'The file sent Maya.', 'Maya was sent the file did.', 'Sent Maya file was.', 0, 'The object becomes the subject of the passive.'), Q('A statement can become a question by…', 'moving a helping verb forward', 'deleting the verb', 'adding a plural', 'removing the subject always', 0, 'She left. Did she leave?'), Q('Transformation should keep…', 'the meaning', 'none of the words ever', 'only the commas', 'a new fact', 0, 'The shape changes. The message should not.'), Q('Which pair matches?', 'We missed the bus. / The bus was missed by us.', 'We missed the bus. / The bus missed we.', 'She is tired. / Tired she is being a different fact.', 'I left. / Left I no.', 0, 'The passive keeps the same event.')]),
  R('intermediate', 'Sentence Construction', 'INT-16', 'Combining and rearranging sentences',
    'Short sentences can be combined so the relationship between them is clear.',
    'The bus was late. We walked. → Because the bus was late, we walked.',
    'Because shows the reason instead of leaving two bare facts.',
    'The bus was late we walked.',
    'The combine has no relationship word.',
    [Q('A clear way to join a reason is…', 'Because the bus was late, we walked.', 'The bus was late we walked.', 'Late bus walked we.', 'Because, walked.', 0, 'Because states the reason.'), Q('But shows…', 'contrast', 'a plural', 'ownership', 'a clock time', 0, 'We ran, but we missed it.'), Q('Rearranging should not…', 'change who did the action by accident', 'use a capital', 'keep the meaning', 'use a verb', 0, 'The file sent Maya is a different event.'), Q('Which combine is clear?', 'She was tired, so she sat down.', 'She was tired she sat down.', 'Tired so she.', 'Sat she tired was.', 0, 'So shows the result.')]),
  R('intermediate', 'Advanced Grammar (most)', 'INT-17', 'Active and passive voice',
    'Active voice says who does the action. Passive voice says what receives it.',
    'Priya wrote the note. The note was written by Priya.',
    'The first names the doer first. The second names the note first.',
    'The note wrote Priya.',
    'The receiver has become the doer.',
    [Q('“Priya wrote the note” is…', 'active', 'passive', 'a fragment', 'a plural', 0, 'The doer is the subject.'), Q('“The note was written by Priya” is…', 'passive', 'active', 'a command', 'an infinitive only', 0, 'Was written moves the focus to the note.'), Q('Passive voice needs a form of be plus…', 'the past participle', 'the -ing form only', 'an article', 'a capital', 0, 'Was written, is sent, were taken.'), Q('Choose the passive.', 'The seats were saved.', 'We saved the seats.', 'Save the seats.', 'We seats.', 0, 'Were saved does not start with the doer.')]),
  R('intermediate', 'Advanced Grammar (most)', 'INT-18', 'Direct and indirect speech',
    'Direct speech quotes the words. Indirect speech reports them and usually shifts the tense.',
    'Maya said, “I am late.” Maya said that she was late.',
    'The quote keeps am. The report shifts to was and she.',
    'Maya said that I am late, when she was talking about herself yesterday.',
    'The pronoun and the tense were not shifted.',
    [Q('Direct speech uses…', 'quotation marks', 'only the word that', 'a passive always', 'no verb', 0, 'The exact words sit inside the marks.'), Q('“I am tired,” she said, is often reported as…', 'She said that she was tired.', 'She said that I am tired.', 'She said she tired.', 'Said she am tired.', 0, 'I becomes she and am becomes was.'), Q('That in indirect speech…', 'introduces the report', 'is always a relative for a bus', 'makes a plural', 'is a modal', 0, 'She said that she was tired.'), Q('Which keeps the exact words?', 'He said, “Wait.”', 'He said that we should wait.', 'He told us to wait.', 'He said to wait.', 0, 'The quotation is direct speech.')]),
  R('intermediate', 'Advanced Grammar (most)', 'INT-19', 'Reported questions and commands',
    'Reported questions use statement word order. Reported commands often use to plus the verb.',
    'She asked where I was. She told me to wait.',
    'Where I was, not where was I. To wait reports the command.',
    'She asked where was I. She told me wait.',
    'The question order stays, and the command has no to.',
    [Q('Report “Where are you?” as…', 'She asked where I was.', 'She asked where was I.', 'She asked where I am being you.', 'Asked where are you she.', 0, 'Reported questions use statement order.'), Q('Report “Wait.” as…', 'She told me to wait.', 'She told me wait.', 'She asked wait I.', 'She said waiting me.', 0, 'Tell plus to plus the base verb.'), Q('Asked is for…', 'questions', 'commands only', 'plurals', 'capitals', 0, 'She asked if we were ready.'), Q('“Did you leave?” can be reported as…', 'He asked if I had left.', 'He asked did I leave.', 'He asked if did I leave.', 'Asked he leave did.', 0, 'If replaces the question form, and the tense shifts.')]),
  R('intermediate', 'Advanced Grammar (most)', 'INT-20', 'Gerunds versus infinitives',
    'Some verbs are followed by a gerund, some by an infinitive, and a few by either with a change in meaning.',
    'She enjoys reading. She decided to leave.',
    'Enjoy takes the gerund. Decide takes the infinitive.',
    'She enjoys to read. She decided leaving.',
    'The forms after those verbs are swapped.',
    [Q('Enjoy is followed by…', 'a gerund', 'an infinitive in the usual pattern', 'a past participle only', 'an article', 0, 'She enjoys reading.'), Q('Decide is followed by…', 'an infinitive', 'a gerund in the usual pattern', 'a plural noun', 'a comma', 0, 'She decided to leave.'), Q('“I stopped to text” means…', 'I paused in order to text', 'I no longer text', 'text is a noun only', 'I never had a phone', 0, 'The infinitive gives the purpose of stopping.'), Q('“I stopped texting” means…', 'I no longer do it', 'I paused so I could start', 'texting is a place', 'stopped is an adjective', 0, 'The gerund is the activity that ended.')]),
  R('intermediate', 'Advanced Grammar (most)', 'INT-21', 'Participial phrases',
    'A participial phrase begins with a participle and describes a noun, usually the subject.',
    'Rushing for the bus, Maya dropped her phone.',
    'Rushing describes Maya, the subject.',
    'Rushing for the bus, the phone dropped Maya.',
    'The phrase is attached to the wrong noun.',
    [Q('In the clear sentence, rushing describes…', 'Maya', 'the phone', 'the bus as the one rushing', 'dropped', 0, 'Maya is the one rushing.'), Q('A dangling participle…', 'is attached to the wrong noun', 'is always correct', 'replaces a subject on purpose', 'is a spelling rule', 0, 'The phone cannot be the one rushing.'), Q('A present participle ends in…', '-ing', '-est', 'a capital', 'to', 0, 'Rushing, waiting, hoping.'), Q('Which line is attached correctly?', 'Carrying the bag, she boarded.', 'Carrying the bag, the bus left her.', 'Left the bus, carrying.', 'Bag carrying she the.', 0, 'She is the one carrying the bag.')]),
  R('intermediate', 'Advanced Grammar (most)', 'INT-22', 'Comparison structures',
    'As…as, more than, and the most mark different kinds of comparison.',
    'This seat is as wide as that one. It is the most comfortable on the bus.',
    'As…as says they match. The most picks one from a group.',
    'This seat is as wider as that one.',
    'The comparative ending and as…as are mixed.',
    [Q('Equal comparison uses…', 'as wide as', 'more wide as', 'the most as', 'wider as', 0, 'As…as is the equal pattern.'), Q('“Than” appears with…', 'a comparative', 'as…as', 'a plural only', 'an article only', 0, 'Bigger than, more careful than.'), Q('The whole group takes…', 'the most or the -est form', 'as…as only', 'than without a comparative', 'a command', 0, 'The most comfortable on the bus.'), Q('Which line is well formed?', 'She is as tall as Maya.', 'She is as taller as Maya.', 'She is more tall as Maya.', 'She is the taller as the class.', 0, 'As tall as compares equals.')]),
  R('intermediate', 'Advanced Grammar (most)', 'INT-23', 'Parallel structure',
    'Items in a pair or a list should use the same grammatical shape.',
    'She likes reading, writing, and drawing.',
    'Three gerunds match.',
    'She likes reading, to write, and draws.',
    'The three items use three different shapes.',
    [Q('Which list is parallel?', 'reading, writing, and drawing', 'reading, to write, and draws', 'to read, writing, and drew', 'read, to writing, and drawed', 0, 'The gerunds match.'), Q('Parallel structure matters in…', 'lists and paired ideas', 'capital letters only', 'plurals of bus', 'question marks only', 0, 'The items should share a shape.'), Q('“She wanted to sit and to wait” is parallel because both parts use…', 'to plus a verb', 'a gerund and a noun', 'two tenses', 'an adjective and a verb', 0, 'The infinitives match.'), Q('Fix “fast, careful, and quietly.”', 'fast, careful, and quiet', 'fast, carefully, and quietly if all are adverbs', 'fastly, careful, quietly', 'a fast and quietly careful', 0, 'If they describe a noun, the adjectives should match. If they describe an action, use adverbs throughout.')]),
  R('intermediate', 'Advanced Grammar (most)', 'INT-24', 'Common collocations',
    'A collocation is a word partnership that sounds natural to a fluent speaker.',
    'Make a mistake. Do your homework. Catch the bus.',
    'Those verbs partner with those nouns.',
    'Do a mistake. Make your homework.',
    'The verbs are paired with the wrong nouns.',
    [Q('The natural partner of mistake is…', 'make', 'do', 'catch', 'tell a mistake', 0, 'Make a mistake.'), Q('Homework usually goes with…', 'do', 'make', 'say', 'a do homework make', 0, 'Do your homework.'), Q('You ___ the bus.', 'catch', 'do', 'make', 'tell', 0, 'Catch the bus is the collocation.'), Q('Which line sounds natural?', 'heavy rain', 'strong rain in this usual pair', 'big rain as the normal phrase', 'fat rain', 0, 'Heavy rain is the partnership English uses.')]),
  R('intermediate', 'Advanced Grammar (most)', 'INT-25', 'Idioms and appropriate usage',
    'An idiom means something other than the literal words, and it has to fit the situation.',
    'She said the quiz was a piece of cake.',
    'That means the quiz was easy, not a dessert.',
    'She said the quiz was a piece of cake to a formal board as slang she did not intend.',
    'The meaning may be clear to friends and odd in a formal room.',
    [Q('“A piece of cake” often means…', 'easy', 'a dessert you must bring', 'impossible', 'late', 0, 'The words are not literal.'), Q('An idiom should…', 'fit the audience', 'be used in every formal email', 'replace every verb', 'avoid meaning', 0, 'Friends may enjoy it. A formal report may not.'), Q('“Hit the books” means…', 'study', 'strike a library shelf', 'throw a book', 'finish a meal', 0, 'The meaning is not literal.'), Q('Which use is literal, not an idiom?', 'She ate a piece of cake.', 'The test was a piece of cake.', 'We hit the books.', 'Hold your horses.', 0, 'Here cake is actual food.')]),
  R('intermediate', 'Accuracy in Writing (rest)', 'INT-26', 'Misplaced and dangling modifiers',
    'Put a describing phrase next to the word it describes.',
    'Maya saw a bus rushing down the road.',
    'If Maya is rushing, say Rushing down the road, Maya saw a bus.',
    'Rushing down the road, a bus was seen by Maya when Maya is the one rushing.',
    'The phrase is closer to the bus than to Maya.',
    [Q('A misplaced modifier…', 'sits too far from the word it describes', 'is always at the start on purpose', 'is a spelling error only', 'replaces the verb', 0, 'The reader attaches it to the wrong word.'), Q('If Maya is the one rushing, write…', 'Rushing down the road, Maya saw a bus.', 'Rushing down the road, a bus appeared.', 'A bus rushing Maya saw.', 'Saw rushing Maya bus the.', 0, 'The phrase is next to Maya.'), Q('A dangling modifier has…', 'nothing correct in the sentence to attach to', 'a perfect subject', 'two objects', 'a capital only', 0, 'The described person is missing.'), Q('“I only texted Maya” can mean…', 'texting was the only action, or Maya was the only person, depending on placement', 'a plural', 'a past participle', 'an article', 0, 'Only should sit next to the word it limits.')]),
  R('intermediate', 'Accuracy in Writing (rest)', 'INT-27', 'Commonly confused words',
    'Some pairs look or sound alike and mean different things.',
    'The delay affected the plan. The effect was a late bus.',
    'Affect is usually the verb. Effect is usually the noun.',
    'The delay effected the plan when you mean influenced it. The affect was late.',
    'The usual verb and noun are swapped.',
    [Q('Which word is usually the verb meaning to influence?', 'affect', 'effect', 'a effect', 'effects as a noun only', 0, 'The delay affected the plan.'), Q('“The effect” is usually…', 'a noun', 'a helping verb', 'a pronoun', 'a command', 0, 'The effect was a late bus.'), Q('Their, there, or they’re: belonging to them is…', 'their', 'there', 'they’re', 'thier', 0, 'Their shows ownership.'), Q('You’re means…', 'you are', 'belonging to you', 'a place', 'your bag', 0, 'The apostrophe marks are.')]),
  R('intermediate', 'Accuracy in Writing (rest)', 'INT-28', 'Common grammatical errors',
    'A few slips show up constantly: agreement, tense, double negatives, and the wrong pronoun form.',
    'She doesn’t have a pass, and they were late.',
    'Doesn’t matches she. Were matches they.',
    'She don’t have no pass, and they was late.',
    'Agreement, a double negative, and was for they all slip.',
    [Q('She ___ want to be late.', 'doesn’t', 'don’t', 'not', 'doesn’t not', 0, 'Doesn’t agrees with she.'), Q('They ___ waiting.', 'were', 'was', 'is being a plural was', 'be', 0, 'They takes were.'), Q('Avoid…', 'don’t have no', 'does not have', 'cannot find', 'did not leave', 0, 'One negative is enough.'), Q('“Me and her went” is better as…', 'She and I went.', 'Her and me went.', 'Me went and her.', 'Went me her.', 0, 'Subject pronouns belong in the subject.')]),
  R('intermediate', 'Accuracy in Writing (rest)', 'INT-29', 'Formal and informal English',
    'The grammar can be correct and still sound wrong for the room.',
    'I will arrive a few minutes late.',
    'That is clear enough for a teacher.',
    'Gonna be late lol.',
    'That fits a friend’s text, not a teacher’s inbox.',
    [Q('Which line belongs in an email to a teacher?', 'I will arrive a few minutes late.', 'gonna be late', 'u there', 'save me a seat or else', 0, 'Will arrive keeps a formal register.'), Q('Gonna is…', 'informal', 'required in essays', 'a past participle', 'an article', 0, 'It stands in for going to among friends.'), Q('Could you… is useful when you want to…', 'sound polite', 'sound angry', 'remove the verb', 'make a plural', 0, 'Could you save a seat?'), Q('Same news, two rooms. A friend may hear…', 'Gonna be late.', 'I wished to inform you of a delay.', 'Dear Sir or Madam only', 'Pursuant to the bus.', 0, 'The short form matches a close friend.')]),
  R('intermediate', 'Accuracy in Writing (rest)', 'INT-30', 'Paragraph construction',
    'A paragraph usually has one main idea, a few supporting sentences, and a closing line.',
    'We missed the bus. The stop clock was wrong, and we left class late. Next time we will leave five minutes earlier.',
    'The first sentence is the point. The middle gives reasons. The last looks ahead.',
    'We missed the bus. Fries are salty. Monday is a day. Phones are loud.',
    'The sentences do not share one idea.',
    [Q('A paragraph should mainly…', 'stick to one idea', 'change topic every sentence', 'avoid verbs', 'be one word', 0, 'The reader should feel a single point.'), Q('The first sentence often…', 'states the point', 'introduces a new unrelated topic', 'is a fragment on purpose', 'hides the idea', 0, 'We missed the bus tells the point.'), Q('Supporting sentences…', 'explain or give reasons', 'contradict the topic with new subjects', 'remove the verb', 'are always questions', 0, 'The clock and the late exit explain the miss.'), Q('Which group is one paragraph idea?', 'missed bus, wrong clock, left late', 'missed bus, salty fries, loud phones', 'Monday, a cat, a comma', 'three unrelated jokes', 0, 'Those details belong together.')]),
  R('intermediate', 'Accuracy in Writing (rest)', 'INT-31', 'Editing and proofreading',
    'Editing checks meaning and structure. Proofreading checks surface slips.',
    'Read once for the point, then once for capitals, agreement, and full stops.',
    'The two passes catch different problems.',
    'Change nothing and call it checked.',
    'A single glance misses both kinds of error.',
    [Q('Proofreading looks mainly for…', 'slips such as spelling, capitals, and punctuation', 'a new plot', 'a different assignment', 'longer paragraphs only', 0, 'It is the surface pass.'), Q('Editing may ask…', 'Does this sentence belong?', 'Is the full stop a circle?', 'How many letters in bus?', 'Is the font blue?', 0, 'Editing cares about structure and meaning.'), Q('A useful order is…', 'meaning first, then surface slips', 'surface only', 'never reread', 'delete the point', 0, 'Fix the idea before polishing marks.'), Q('“She don’t leaves.” needs…', 'agreement and a simpler verb: She doesn’t leave.', 'a new topic', 'an idiom', 'a passive only', 0, 'Both the meaning of the verb and the agreement slip.')]),
  R('intermediate', 'Accuracy in Writing (rest)', 'INT-32', 'Roots, prefixes and suffixes',
    'A root carries the core meaning. A prefix comes before it. A suffix comes after.',
    'I reread the unfair comment.',
    'Re- means again. Un- reverses fair.',
    'I unread the refair comment when you mean read again and not fair.',
    'The pieces are attached to the wrong meaning.',
    [Q('Re- often means…', 'again', 'not', 'a person', 'a tense', 0, 'Reread means read again.'), Q('Un- often means…', 'not or the reverse', 'again', 'full of', 'a plural', 0, 'Unfair means not fair.'), Q('-ful in careful means…', 'full of', 'again', 'not', 'past tense', 0, 'Careful means full of care.'), Q('Which word adds a prefix that reverses?', 'unfair', 'careful', 'reader', 'reading', 0, 'Un- flips fair.')]),
  R('intermediate', 'Accuracy in Writing (rest)', 'INT-33', 'Compound words',
    'A compound joins two words into one meaning. It may be open, hyphenated, or closed.',
    'We missed the bus stop and left a goodbye.',
    'Bus stop is open. Goodbye is closed.',
    'We missed the busstop and left a good bye as if the pattern were random.',
    'The spacing does not follow the usual form.',
    [Q('Bus stop is usually written…', 'as two words', 'as busstop', 'as bus-stop in every everyday use', 'as one letter', 0, 'It is an open compound.'), Q('Goodbye is usually…', 'one word', 'good bye', 'good-bye in all modern use only', 'a verb plus to', 0, 'It is a closed compound.'), Q('A compound’s meaning…', 'is shared by the two parts together', 'is always the first word only', 'deletes the second word', 'is a prefix', 0, 'Bus stop is a place, not just a bus.'), Q('Which is a compound?', 'homework', 'the', 'and', 'quickly as one job', 0, 'Home and work have joined.')]),
  R('intermediate', 'Accuracy in Writing (rest)', 'INT-34', 'Homophones, homonyms and homographs',
    'Homophones sound alike. Homonyms share a spelling or sound. Homographs share a spelling and may differ in sound.',
    'We ate two fries, too. She read the note, and she will read another.',
    'Ate and eight sound different; two, too, and to sound alike. Read is spelled the same for two pronunciations.',
    'We eight too fries to.',
    'The sound-alikes are swapped.',
    [Q('Two, too, and to are…', 'homophones', 'the same meaning', 'prefixes', 'tenses', 0, 'They sound alike and mean different things.'), Q('Read (present) and read (past) are…', 'homographs', 'homophones with different spelling', 'articles', 'commands', 0, 'Same spelling, different sound and tense.'), Q('Their and there…', 'sound alike and mean different things', 'are both possessives', 'are both places', 'are verbs', 0, 'That is why they are confused.'), Q('Choose the homophone that means also.', 'too', 'two', 'to', 'toe', 0, 'Too means also or excessive.')]),
  R('intermediate', 'Accuracy in Writing (rest)', 'INT-35', 'Synonyms and antonyms',
    'A synonym is close in meaning. An antonym is opposite.',
    'The bus was late, not early. It was delayed.',
    'Late and delayed are close. Early is the opposite of late.',
    'The bus was late, which means early.',
    'The opposite has been treated as a synonym.',
    [Q('A synonym for late in this context is…', 'delayed', 'early', 'quiet', 'plural', 0, 'Delayed is close to late.'), Q('An antonym of late is…', 'early', 'delayed', 'tardy', 'behind', 0, 'Early is the opposite.'), Q('Big and large are…', 'synonyms', 'antonyms', 'homophones', 'articles', 0, 'They are close in meaning.'), Q('Start and finish are…', 'antonyms', 'the same verb', 'prefixes', 'spellings of one word', 0, 'They point in opposite directions.')]),
  R('intermediate', 'Accuracy in Writing (rest)', 'INT-36', 'Word families and changing parts of speech',
    'Words in a family share a root and change job with a suffix.',
    'Decide, decision, decisive. She made a decision.',
    'Decide is the verb. Decision is the noun.',
    'She made a decide.',
    'The verb form is sitting where a noun is needed.',
    [Q('Decision is the noun from…', 'decide', 'bus', 'quick', 'they', 0, 'The family shares the root.'), Q('“Her ___ was quick.”', 'decision', 'decide', 'deciding as the only noun here', 'decidedly noun', 0, 'The blank needs a noun.'), Q('Quick, quickly, and quickness are…', 'a word family', 'unrelated', 'three tenses of be', 'articles', 0, 'The suffix changes the job.'), Q('A suffix can…', 'change the part of speech', 'delete the meaning always', 'replace the subject', 'remove spelling', 0, '-ion, -ly, and -ness do that work.')]),
  R('intermediate', 'Verb and tense usage (basic parts)', 'INT-37', 'Future forms: will, going to, and present continuous',
    'Will often marks a decision made now. Going to marks a plan. The present continuous can mark an arrangement.',
    'The bus is late, so I will walk. I am meeting Priya at 4.',
    'Will is the new decision. Am meeting is already arranged.',
    'I will meeting Priya at 4. I am walk because I just decided.',
    'The forms are attached to the wrong kind of future.',
    [Q('A decision you make while speaking uses…', 'will', 'a past participle alone', 'had left', 'an article', 0, 'I will walk.'), Q('An arrangement with a time often uses…', 'the present continuous', 'will plus -ing', 'a noun only', 'was', 0, 'I am meeting Priya at 4.'), Q('Going to fits…', 'a plan you already have', 'a past fact', 'a fragment', 'a plural', 0, 'I am going to catch the early bus.'), Q('Which pair matches?', 'just decided → will; already arranged → am meeting', 'just decided → had met; arranged → a noun', 'will → yesterday', 'am meeting → a finished past', 0, 'The form follows the kind of future.')]),
  R('intermediate', 'Verb and tense usage (basic parts)', 'INT-38', 'Perfect and perfect-continuous forms',
    'The perfect links an earlier time to a later one. The perfect continuous stresses the length of that activity.',
    'I have missed two buses. I have been waiting since 7.',
    'Have missed looks at the result. Have been waiting looks at the time spent.',
    'I have miss two buses since I am wait.',
    'The participle and the continuous piece are incomplete.',
    [Q('“I have lost my pass” links the loss to…', 'now', 'a future plan only', 'a command', 'a noun', 0, 'The present perfect reaches the present.'), Q('Since 7 with a waiting activity prefers…', 'have been waiting', 'wait', 'am wait', 'waited since as a habit of tomorrow', 0, 'The perfect continuous shows duration.'), Q('Had left means the leaving happened…', 'before another past moment', 'in the future', 'as a noun', 'without a subject ever', 0, 'The bus had left before we arrived.'), Q('Which line shows duration?', 'She has been texting for an hour.', 'She texts.', 'She texted once.', 'A text.', 0, 'Has been texting covers the stretch of time.')]),
  R('intermediate', 'Verb and tense usage (basic parts)', 'INT-39', 'Tense consistency in writing',
    'Stay in one time unless the meaning really changes time.',
    'We missed the bus, walked, and arrived late.',
    'Three past verbs tell one past story.',
    'We missed the bus, walk, and arrive late.',
    'The story jumps tense for no reason.',
    [Q('A past story should mostly use…', 'past verbs', 'a new tense every clause', 'only future', 'no verbs', 0, 'Missed, walked, arrived.'), Q('Change tense when…', 'the time of the events really changes', 'you want variety', 'a noun is plural', 'you add a comma', 0, 'We missed it, and now we are walking.'), Q('Which paragraph is consistent?', 'She left, texted, and waited.', 'She left, texts, and waited.', 'She leaves, texted, and waits yesterday.', 'Left she texts waited.', 0, 'All three verbs are past.'), Q('“Yesterday I leave” should be…', 'Yesterday I left.', 'Yesterday I am leave.', 'Yesterday I leaving.', 'Leave yesterday I.', 0, 'Yesterday requires the past.')]),
  R('intermediate', 'Meaning and communication (everyday)', 'INT-40', 'Requests, permission, advice and obligation',
    'Can, could, may, should, and must separate a soft request from a duty.',
    'Could you save a seat? You must show your pass.',
    'Could you is a polite request. Must is an obligation.',
    'You must maybe save a seat if you only want to be polite. Could you show your pass as a rule.',
    'The strength of the modal does not match the situation.',
    [Q('A polite request is…', 'Could you save a seat?', 'You must save a seat or else.', 'Save.', 'Seat you could.', 0, 'Could you softens the request.'), Q('Must often marks…', 'obligation', 'a casual guess only', 'a plural', 'a nickname', 0, 'You must show your pass.'), Q('Should often marks…', 'advice', 'a finished fact', 'ownership', 'a capital', 0, 'You should leave earlier.'), Q('May I sit here? asks for…', 'permission', 'a past time', 'a synonym', 'a fragment', 0, 'May I is a permission question.')]),
  R('intermediate', 'Meaning and communication (everyday)', 'INT-41', 'Ability, possibility, probability and certainty',
    'Can marks ability. Might marks a weak possibility. Must can mark a strong conclusion.',
    'I can hear the bus. It might be late. That must be our stop.',
    'Can is ability. Might is unsure. Must here is a confident conclusion.',
    'I might hear it if the sound is certain, and I must hear it if I am only guessing weakly.',
    'The strength of the modal does not match the evidence.',
    [Q('Ability uses…', 'can', 'might for a skill you definitely have', 'a noun', 'must for a maybe', 0, 'I can hear it.'), Q('A weak possibility uses…', 'might', 'must as a guess with little evidence', 'can as a finished fact', 'a full stop only', 0, 'It might be late.'), Q('“That must be our stop” means…', 'I am almost sure', 'I have no idea', 'it was a noun', 'stop is past', 0, 'Must draws a strong conclusion.'), Q('Which is the least sure?', 'She might come.', 'She will come.', 'She is here.', 'She came.', 0, 'Might leaves the result open.')]),
  R('intermediate', 'Meaning and communication (everyday)', 'INT-42', 'Offers, suggestions and invitations',
    'Offers, suggestions, and invitations use different patterns.',
    'I will grab your hoodie. Shall we walk? Would you like to come?',
    'Will offers. Shall we suggests. Would you like invites.',
    'I grab your hoodie as an offer with no modal. You come.',
    'The inviting and offering language is missing.',
    [Q('An offer of help can be…', 'I will grab your hoodie.', 'Grab.', 'You grab it.', 'Hoodie will.', 0, 'Will volunteers the action.'), Q('Shall we… is a…', 'suggestion', 'strong order', 'past fact', 'plural noun', 0, 'It invites a shared decision.'), Q('Would you like to come? is an…', 'invitation', 'refusal', 'article', 'past participle', 0, 'It asks the other person to join.'), Q('Which is the softest invitation?', 'Would you like to sit with us?', 'Sit.', 'You sit now.', 'Sitting.', 0, 'Would you like leaves room to say no.')]),
  R('intermediate', 'Meaning and communication (everyday)', 'INT-43', 'Agreement and disagreement',
    'Agree and disagree in a way that matches how well you know the person.',
    'I see what you mean, but I think we should wait.',
    'The first clause respects the other view. But introduces yours.',
    'You’re wrong, shut up.',
    'The disagreement attacks the person.',
    [Q('A respectful disagreement can start with…', 'I see what you mean, but…', 'No, you’re silly.', 'Wrong.', 'Shut the idea.', 0, 'It acknowledges the other person first.'), Q('I agree means…', 'you share the view', 'you refuse it', 'you leave', 'you own it', 0, 'Agree is the same side.'), Q('But after a partial agreement signals…', 'a different view', 'a plural', 'a name', 'a tense', 0, 'The contrast follows.'), Q('Which reply disagrees politely?', 'I’m not sure that’s right.', 'That’s stupid.', 'No way, idiot.', 'False, you.', 0, 'It challenges the idea, not the person.')]),
  R('intermediate', 'Meaning and communication (everyday)', 'INT-44', 'Making comparisons and expressing preferences',
    'Prefer, would rather, and comparison forms say which option you want.',
    'I prefer the early bus. I would rather walk than wait.',
    'Prefer takes the noun. Would rather takes the base verb.',
    'I prefer walk than the bus. I would rather to wait.',
    'The patterns after prefer and would rather are mixed up.',
    [Q('Prefer is often followed by…', 'a noun or a gerund', 'the base verb with rather’s pattern', 'a past participle only', 'an article only', 0, 'I prefer walking. I prefer the early bus.'), Q('Would rather is followed by…', 'the base verb', 'to plus verb in the usual pattern', 'a plural noun always', 'an -ing form always', 0, 'I would rather walk.'), Q('Than joins…', 'the option you reject', 'a capital', 'a question', 'an article', 0, 'Rather walk than wait.'), Q('Which line states a preference clearly?', 'I would rather walk than wait.', 'I rather to walking than.', 'Prefer I wait walk.', 'Than walk rather.', 0, 'The base verbs match on both sides of than.')]),
  R('intermediate', 'Meaning and communication (everyday)', 'INT-45', 'Polite and indirect questions',
    'An indirect question asks softly and uses statement word order.',
    'Could you tell me where the stop is?',
    'Where the stop is, not where is the stop, after the polite opening.',
    'Could you tell me where is the stop?',
    'The question order stays inside the indirect question.',
    [Q('Inside “Can you tell me…”, use…', 'statement order', 'question order', 'no verb', 'a command', 0, 'Where the stop is.'), Q('A polite opener is…', 'Could you tell me…?', 'Tell me now.', 'Where.', 'Say.', 0, 'Could you softens the question.'), Q('Which line is indirect and well formed?', 'Do you know if she left?', 'Do you know did she leave?', 'Know you if left she?', 'If did she leave know?', 0, 'If she left uses statement order.'), Q('Indirect questions are useful when you want to sound…', 'less abrupt', 'angry', 'past tense only', 'plural', 0, 'They give the other person room.')]),
  R('advanced', 'From Advanced Grammar', 'ADV-01', 'Emphasis and inversion',
    'Moving a negative or limiting phrase to the front, and flipping the helping verb, puts weight on that phrase.',
    'Never have I seen a bus that late.',
    'Never is fronted, so have comes before I.',
    'Never I have seen a bus that late.',
    'The helping verb stays after the subject, so the emphasis pattern is incomplete.',
    [Q('After a negative opener such as never, the usual pattern is…', 'helping verb before the subject', 'subject before the helping verb', 'no verb', 'a plural noun', 0, 'Never have I, not Never I have.'), Q('“Rarely do we catch it” emphasises…', 'how seldom it happens', 'that we always catch it', 'a person named Rarely', 'the noun bus', 0, 'Rarely plus inversion spotlights the rarity.'), Q('Which line uses inversion for emphasis?', 'Little did she know the bus had left.', 'Little she knew the bus had left.', 'She little did know.', 'Did little she.', 0, 'Little did she know flips did in front of she.'), Q('Inversion here changes…', 'the focus, while the basic meaning stays', 'who took the bus', 'the spelling of never', 'the number of nouns', 0, 'The event is the same. The fronted word gets the stress.')]),
  R('advanced', 'Nouns, pronouns and determiners', 'ADV-02', 'Concrete and abstract nouns',
    'A concrete noun names something you can sense. An abstract noun names an idea, feeling, or quality.',
    'The delay caused real anxiety.',
    'Delay can be noticed in time. Anxiety is a feeling, so it is abstract.',
    'The anxiety sat on the seat next to the delay as if both were objects you could pick up.',
    'A feeling is treated as if it were a thing you can touch.',
    [Q('Which noun is abstract?', 'honesty', 'bus', 'phone', 'seat', 0, 'Honesty is a quality. The others can be seen or touched.'), Q('Which noun is concrete?', 'hoodie', 'relief', 'silence', 'freedom', 0, 'A hoodie is a physical thing.'), Q('“The silence in the hallway” uses silence as…', 'an abstract noun', 'a verb', 'an article', 'a concrete object you can carry', 0, 'Silence names a quality of the place, not a thing you hold.'), Q('A concrete noun is one you can…', 'see, hear, or touch', 'only feel as an idea', 'never use as a subject', 'always capitalise', 0, 'Bus, phone, and rain are available to the senses.')]),
  R('advanced', 'Nouns, pronouns and determiners', 'ADV-03', 'Collective nouns and agreement',
    'A collective noun names a group. It can take a singular verb when the group acts as one, and a plural verb when the members act separately.',
    'The team is on the bus. The team are arguing about the playlist.',
    'Is treats the team as one unit. Are treats the members as individuals.',
    'The team are on the bus if you mean one vehicle as a single unit, and the team is arguing if you mean each person is arguing a different point.',
    'The verb does not match whether you mean the unit or the members.',
    [Q('When the group acts as one, choose…', 'a singular verb', 'a plural verb', 'no verb', 'a past participle only', 0, 'The class is waiting.'), Q('“The jury are divided” treats the jury as…', 'separate people', 'one single mind', 'a place', 'an article', 0, 'Divided points at the members, so a plural verb fits.'), Q('Which line matches a united group?', 'The class is ready.', 'The class are a single ready thing.', 'Class ready is.', 'Is the class are.', 0, 'Is matches one unit.'), Q('A collective noun names…', 'a group', 'one person’s feeling only', 'a helping verb', 'a suffix', 0, 'Team, class, and jury are groups.')]),
  R('advanced', 'Nouns, pronouns and determiners', 'ADV-04', 'Case of nouns and pronouns',
    'Subject pronouns do the action. Object pronouns receive it. Possessive forms show ownership.',
    'She texted me, and the reply was hers.',
    'She is the subject, me is the object, and hers shows ownership.',
    'Her texted I, and the reply was she.',
    'The subject, object, and possessive forms are swapped.',
    [Q('Which pronoun can be the subject?', 'she', 'her', 'me', 'him', 0, 'She texted me. Her cannot be the doer.'), Q('The object of “texted” in “She texted me” is…', 'me', 'she', 'texted', 'a noun only', 0, 'Me receives the text.'), Q('Hers is…', 'a possessive pronoun', 'a subject pronoun', 'a verb', 'an article', 0, 'The reply was hers.'), Q('“Maya and ___ left” needs…', 'I', 'me', 'hers', 'my', 0, 'I is a subject, paired with Maya before the verb.')]),
  R('advanced', 'Nouns, pronouns and determiners', 'ADV-05', 'Reflexive and emphatic pronouns',
    'A reflexive pronoun shows that the subject and the object are the same person. An emphatic pronoun simply stresses who did it.',
    'She blamed herself. She herself sent the file.',
    'Herself is the object of blamed. In the second line, herself only emphasises she.',
    'She blamed her when she means she is the one at fault. Myself sent the file.',
    'The reflexive is missing where the subject is the object, and myself cannot be the subject.',
    [Q('“She taught herself the chord” uses herself as…', 'a reflexive pronoun', 'a subject', 'an article', 'a tense', 0, 'The subject and the object are the same person.'), Q('“I myself checked the time” uses myself to…', 'add emphasis', 'replace the subject', 'make a plural', 'show a new person', 0, 'I is already the subject. Myself stresses it.'), Q('Which line is well formed?', 'He hurt himself.', 'He hurt hisself.', 'Himself hurt he.', 'Me hurt myself as the subject.', 0, 'Himself matches he.'), Q('A reflexive pronoun…', 'points back to the subject', 'always means a different person', 'is a preposition', 'replaces the verb', 0, 'Herself, himself, and themselves point back.')]),
  R('advanced', 'Nouns, pronouns and determiners', 'ADV-06', 'Indefinite and reciprocal pronouns',
    'Indefinite pronouns such as someone and everyone do not name a particular person. Reciprocal pronouns show an exchange between people.',
    'Someone left a seat. Maya and Priya texted each other.',
    'Someone is unnamed. Each other means the texting went both ways.',
    'Someone left their named passport of Maya only. Maya texted each other.',
    'An indefinite pronoun is treated as a named person, and each other needs more than one person.',
    [Q('Someone is…', 'an indefinite pronoun', 'a reciprocal pronoun', 'a named person', 'a verb', 0, 'It does not say who.'), Q('Each other shows…', 'an action that goes both ways', 'one person acting alone', 'a place', 'a tense', 0, 'They helped each other.'), Q('One another usually refers to…', 'more than two people in an exchange', 'one person', 'a bus', 'a capital letter', 0, 'The whole group blamed one another.'), Q('Which line uses a reciprocal pronoun correctly?', 'The two friends called each other.', 'Maya called each other.', 'Someone called each other alone.', 'Each other called.', 0, 'Two people are required for each other.')]),
  R('advanced', 'Nouns, pronouns and determiners', 'ADV-07', 'Demonstratives',
    'This and these point to something near. That and those point to something farther away. This and that are singular. These and those are plural.',
    'This seat is free. Those buses have left.',
    'This is one nearby seat. Those is more than one bus at a distance.',
    'These seat is free. That buses have left.',
    'The singular and plural demonstratives are swapped.',
    [Q('One thing nearby takes…', 'this', 'these', 'those', 'them', 0, 'This seat, not these seat.'), Q('More than one thing farther away takes…', 'those', 'this', 'that', 'a', 0, 'Those buses.'), Q('These agrees with…', 'a plural noun', 'a singular noun', 'a verb only', 'an adverb', 0, 'These seats, not these seat.'), Q('Which line matches number and distance?', 'That stop is across the road.', 'Those stop is across the road.', 'This buses are here.', 'These bus.', 0, 'That is singular and points farther away.')]),
  R('advanced', 'Nouns, pronouns and determiners', 'ADV-08', 'Distributives: each, every, either, and neither',
    'Each and every single out members of a group and take a singular verb. Either and neither choose between options.',
    'Each student has a pass. Neither bus is on time.',
    'Each and neither take a singular verb.',
    'Each students has a pass. Neither buses is on time.',
    'The noun after each and neither should be singular here.',
    [Q('Every takes…', 'a singular verb', 'a plural verb', 'no noun', 'a past participle as the subject', 0, 'Every seat is taken.'), Q('Neither of the two buses ___ late.', 'is', 'are', 'be', 'were being a required plural', 0, 'Neither is grammatically singular.'), Q('Either means…', 'one or the other', 'both for certain', 'none of a large group', 'the owner', 0, 'Either seat is fine.'), Q('Which line is well formed?', 'Each of the students has a seat.', 'Each of the students have a seat in this careful pattern.', 'Every students has a seat.', 'Neither buses are here.', 0, 'Each takes has, and students is inside the of-phrase.')]),
  R('advanced', 'Nouns, pronouns and determiners', 'ADV-09', 'Quantifiers: much, many, few, little, etc.',
    'Many and few go with countable nouns. Much and little go with uncountable nouns.',
    'Many seats are free. Little time is left.',
    'Seats can be counted. Time cannot, so little fits.',
    'Much seats are free. Many time is left.',
    'The quantifiers are paired with the wrong kind of noun.',
    [Q('Seats take…', 'many', 'much', 'little', 'a much', 0, 'Seats are countable.'), Q('Time, as an amount, takes…', 'much or little', 'many or few', 'these', 'each as a plural', 0, 'Time is uncountable here.'), Q('A few means…', 'a small number of countable things', 'a small amount of water', 'none', 'the owner', 0, 'A few seats.'), Q('Which line matches?', 'We have little hope and many options.', 'We have many hope and much options.', 'Few time is left.', 'Much friends arrived.', 0, 'Hope is uncountable. Options are countable.')]),
  R('advanced', 'Nouns, pronouns and determiners', 'ADV-10', 'Possessive determiners versus possessive pronouns',
    'A possessive determiner comes before a noun. A possessive pronoun stands alone.',
    'That is her seat. That seat is hers.',
    'Her needs the noun seat. Hers replaces her seat.',
    'That is hers seat. That seat is her.',
    'The determiner and the pronoun are in each other’s places.',
    [Q('Before a noun, use…', 'her', 'hers', 'theirs as a determiner', 'ours seat', 0, 'Her seat, their bus, your pass.'), Q('Standing alone, use…', 'hers', 'her', 'my', 'your', 0, 'The seat is hers.'), Q('“Our bus” uses our as…', 'a possessive determiner', 'a possessive pronoun standing alone', 'a verb', 'a reflexive', 0, 'Our comes before bus.'), Q('Which pair is split correctly?', 'my pass / mine', 'mine pass / my', 'hers seat / her', 'their / theirs bus', 0, 'My needs a noun. Mine stands alone.')]),
  R('advanced', 'Verbs and tense usage (advanced)', 'ADV-11', 'Stative and dynamic verbs',
    'Dynamic verbs can take a continuous form. Stative verbs, which describe states, usually stay simple.',
    'I am catching the bus. I know the stop.',
    'Catching is an action in progress. Know is a state, so it stays simple.',
    'I am knowing the stop. I catch the bus right now without a continuous form when the action is in progress.',
    'The state is forced into the continuous, and the action in progress is left simple.',
    [Q('Which verb is usually stative?', 'know', 'run', 'eat', 'text', 0, 'Know describes a state, not an action you watch happening.'), Q('An action in progress can be…', 'I am texting.', 'I am knowing.', 'I am owning the seat.', 'I am believing it for a simple opinion.', 0, 'Texting is dynamic.'), Q('“I have a pass” prefers the simple form because have here means…', 'possession, a state', 'an activity you can watch', 'a future arrangement', 'a command', 0, 'Ownership is stative.'), Q('Which line fits?', 'She understands the rule.', 'She is understanding the rule as a simple state.', 'I am knowing her name.', 'They are owning the bus.', 0, 'Understand stays in the simple form for a state.')]),
  R('advanced', 'Verbs and tense usage (advanced)', 'ADV-12', 'Linking verbs and complements',
    'A linking verb joins the subject to a complement. The complement describes the subject, so it is often an adjective, not an adverb.',
    'The bus seems late. The fries taste salty.',
    'Late describes the bus. Salty describes the fries.',
    'The bus seems lately. The fries taste saltily.',
    'Adverbs are describing the subject as if they described the verb.',
    [Q('After a linking verb, a description of the subject is usually…', 'an adjective', 'an adverb', 'a modal', 'a clause with no subject', 0, 'The bus seems late.'), Q('Which is a linking verb here?', 'taste', 'catch', 'text', 'run', 0, 'The fries taste salty. Taste links fries to salty.'), Q('“She looks tired” means…', 'she appears tired', 'she is looking with her eyes at tired', 'tired is an adverb', 'looks is a noun only', 0, 'Looks links she to the adjective tired.'), Q('Choose the complement that fits.', 'The hallway fell silent.', 'The hallway fell silently if you mean it became quiet.', 'The fries taste salt.', 'She seems tiredly.', 0, 'Silent describes the hallway after fell.')]),
  R('advanced', 'Verbs and tense usage (advanced)', 'ADV-13', 'Causative verbs: have, get, make and let',
    'Have, get, make, and let can mean you cause another person to do something. The pattern after each verb is different.',
    'She had the driver wait. She got him to wait. She made him wait. She let him wait.',
    'Have and make and let take the base verb. Get takes to plus the verb.',
    'She had the driver to wait. She made him to wait. She got him wait.',
    'To is added after have and make, and dropped after get.',
    [Q('Get someone ___ it.', 'to do', 'do, with no to', 'doing as the only pattern', 'done as a command to them', 0, 'She got him to wait.'), Q('Make someone ___ it.', 'do', 'to do', 'doing', 'does', 0, 'She made him wait.'), Q('Let means…', 'allow', 'force with make’s strength', 'finish', 'own', 0, 'She let him wait means she allowed it.'), Q('Which set of patterns is right?', 'have him wait / get him to wait', 'have him to wait / get him wait', 'make him to leave / let him to leave', 'let him leaving', 0, 'Have takes the base verb. Get takes to.')]),
  R('advanced', 'Verbs and tense usage (advanced)', 'ADV-14', 'Participial adjectives: bored/boring',
    'The -ed participle describes how someone feels. The -ing participle describes what causes the feeling.',
    'The delay was boring. We were bored.',
    'Boring describes the delay. Bored describes us.',
    'The delay was bored. We were boring if the delay is what tired us.',
    'The cause and the feeling are swapped.',
    [Q('A film that causes the feeling is…', 'boring', 'bored', 'bore', 'a bored film about us', 0, 'The film is boring. The audience is bored.'), Q('The people who feel it are…', 'bored', 'boring', 'bore', 'bores', 0, 'We were bored.'), Q('“An exciting match” means…', 'the match causes excitement', 'the match feels excited', 'excite is a noun', 'the crowd is the adjective', 0, '-ing describes the source.'), Q('Which pair matches?', 'a tiring day / tired students', 'a tired day / tiring students who feel the day', 'a bored lesson / a boring class of people', 'exciting fans / excited news', 0, 'The day causes the tiredness. The students feel it.')]),
  R('advanced', 'Verbs and tense usage (advanced)', 'ADV-15', 'Used to, be used to and get used to',
    'Used to plus a base verb marks a past habit. Be used to and get used to are followed by a noun or a gerund and mark familiarity.',
    'I used to walk. I am used to walking. I am getting used to the early bus.',
    'Used to walk is the old habit. Am used to walking means walking feels normal now.',
    'I use to walked. I am used to walk as the habit meaning. I used to walking.',
    'The verb form after each pattern is wrong.',
    [Q('A past habit is…', 'I used to walk.', 'I am used to walk.', 'I use to walked.', 'I used to walking.', 0, 'Used to plus the base verb.'), Q('“I am used to waking early” means…', 'waking early feels normal', 'I no longer wake early', 'used is the main past habit with to waking', 'wake is a noun only', 0, 'Be used to is about familiarity.'), Q('Get used to means…', 'become familiar', 'stop a past habit', 'force someone', 'own something', 0, 'I am getting used to the noise.'), Q('Which line is a past habit?', 'She used to take the 7:40.', 'She is used to the 7:40.', 'She is getting used to crowds.', 'Used to the bus she.', 0, 'Used to take names what she did before.')]),
  R('advanced', 'Verbs and tense usage (advanced)', 'ADV-16', 'Present forms used for the future',
    'A present form can point to the future when the future is scheduled, arranged, or part of a timetable.',
    'The bus leaves at 7:40. I am meeting Priya after school.',
    'Leaves is a timetable. Am meeting is an arrangement.',
    'The bus is leave at 7:40. I meet Priya after school if the meeting is a one-off arrangement you want to mark as continuous.',
    'The timetable and the arrangement use the wrong present pattern.',
    [Q('A timetable often uses…', 'the present simple', 'the past perfect', 'used to', 'a modal perfect', 0, 'The bus leaves at 7:40.'), Q('An arrangement you have already made can use…', 'the present continuous', 'the past simple', 'a stative continuous of know', 'had left', 0, 'I am meeting Priya after school.'), Q('“When the bus arrives, we leave” uses present verbs for…', 'a future time', 'a finished past', 'a wish', 'a passive', 0, 'The arrival is still ahead.'), Q('Which line is a schedule?', 'Term ends on Friday.', 'I am knowing Friday.', 'She used to end on Friday.', 'Ended the term will.', 0, 'A fixed future date takes the present simple.')]),
  R('advanced', 'Verbs and tense usage (advanced)', 'ADV-17', 'Modal perfect forms: should have, might have, etc.',
    'A modal plus have plus the past participle looks back and judges a past possibility, duty, or conclusion.',
    'I should have left earlier. She might have missed it.',
    'Should have marks a past duty that did not happen. Might have marks a past possibility.',
    'I should have leave earlier. She might missed it.',
    'Have and the past participle are incomplete.',
    [Q('A regret about the past uses…', 'should have plus the past participle', 'should plus the past participle with no have', 'should having left', 'have should left', 0, 'I should have left earlier.'), Q('“She might have missed it” means…', 'it is possible she missed it', 'she certainly missed it', 'she will miss it', 'miss is a noun', 0, 'Might have is a past possibility.'), Q('Must have draws…', 'a strong conclusion about the past', 'a weak guess about tomorrow', 'a command for now', 'a plural', 0, 'The bus must have left. The stop is empty.'), Q('Which line is formed correctly?', 'You could have texted.', 'You could have text.', 'You could texted.', 'You have could texted.', 0, 'Could have plus the past participle.')]),
  R('advanced', 'Verbs and tense usage (advanced)', 'ADV-18', 'Mood: indicative, imperative and subjunctive',
    'The indicative states a fact. The imperative gives a command. The subjunctive marks a wish, a demand, or an unreal situation.',
    'The bus is late. Wait here. I suggest that she leave early.',
    'Is states a fact. Wait commands. Leave has no -s because the suggestion uses the subjunctive.',
    'I suggest that she leaves early, when the careful subjunctive is wanted. The bus be late as a fact.',
    'The fact is given a subjunctive shape, and the suggestion is given an ordinary -s.',
    [Q('“The bus is late” is…', 'indicative', 'imperative', 'subjunctive', 'a participle', 0, 'It states a fact.'), Q('“Wait here” is…', 'imperative', 'indicative', 'a tense name', 'passive', 0, 'It tells someone what to do.'), Q('After suggest, a careful subjunctive is…', 'that she leave', 'that she leaves as the formal subjunctive', 'that she left yesterday as the wish', 'leave she that', 0, 'The base form leave has no -s.'), Q('“If I were you” uses were because the situation is…', 'unreal', 'a present fact about me', 'a command', 'plural people only', 0, 'Were is the unreal subjunctive.')]),
  R('advanced', 'Sentence relationships', 'ADV-19', 'Compound-complex sentences',
    'A compound-complex sentence has at least two independent clauses and at least one dependent clause.',
    'The bus left, and we walked because the rain started.',
    'The bus left and we walked are independent. Because the rain started is dependent.',
    'Because the rain started.',
    'Only the dependent clause is there.',
    [Q('A compound-complex sentence needs…', 'two independent clauses and one dependent clause', 'one clause only', 'no verb', 'only a phrase', 0, 'That mix is what the name says.'), Q('In “The bus left, and we walked because it rained,” the dependent clause is…', 'because it rained', 'the bus left', 'we walked', 'and', 0, 'Because makes that clause dependent.'), Q('And in that sentence joins…', 'two independent clauses', 'two dependent clauses only', 'a noun to its article', 'nothing', 0, 'The bus left and we walked can each stand.'), Q('Which line is compound-complex?', 'She texted, but I stayed when the rain started.', 'When the rain started.', 'She texted.', 'But I stayed.', 0, 'Texted and stayed are independent. When the rain started depends.')]),
  R('advanced', 'Sentence relationships', 'ADV-20', 'Main, subordinate and coordinate clauses',
    'A main clause can stand alone. A subordinate clause cannot. Coordinate clauses are equals joined by a word such as and or but.',
    'I stayed, but she left because the bus came.',
    'I stayed and she left are coordinate. Because the bus came is subordinate.',
    'Because the bus came, but.',
    'The subordinate clause is left without a main clause, and but has nothing to join.',
    [Q('A subordinate clause…', 'depends on a main clause', 'can always stand alone', 'is always joined by and', 'has no verb', 0, 'Because the bus came cannot be the whole sentence.'), Q('Coordinate clauses are…', 'equal in rank', 'one inside the other', 'phrases without verbs', 'articles', 0, 'And and but join equals.'), Q('The main clause in “Because it rained, we walked” is…', 'we walked', 'because it rained', 'because', 'it', 0, 'We walked can stand alone.'), Q('Which word coordinates?', 'but', 'because', 'although', 'when', 0, 'But joins equals. The others subordinate.')]),
  R('advanced', 'Sentence relationships', 'ADV-21', 'Restrictive and non-restrictive clauses',
    'A restrictive clause identifies which person or thing. A non-restrictive clause adds extra information and is set off with commas.',
    'Students who finish early can leave. Priya, who lent me the charger, is waiting.',
    'Who finish early tells which students. Who lent me the charger is extra, because Priya is already named.',
    'Students, who finish early, can leave if you mean only some students. Priya who lent me the charger is waiting with no commas when the clause is only extra.',
    'The commas do not match whether the clause identifies or merely adds.',
    [Q('A clause that tells you which one is…', 'restrictive', 'non-restrictive', 'always between commas', 'a fragment', 0, 'Who finish early identifies the students.'), Q('Extra information about a person already named takes…', 'commas', 'no commas, so it seems to identify them', 'a question mark', 'a modal', 0, 'Priya, who lent me the charger, is waiting.'), Q('Removing a non-restrictive clause…', 'leaves the main meaning intact', 'makes the noun impossible to identify', 'deletes the verb’s meaning', 'changes the plural', 0, 'Priya is waiting still makes sense.'), Q('Which clause is restrictive?', 'The bus that we missed is gone.', 'Maya, who is my cousin, texted.', 'The coach, who is new, waited.', 'Friday, which was wet, ended.', 0, 'That we missed tells which bus.')]),
  R('advanced', 'Sentence relationships', 'ADV-22', 'Relative-clause reduction',
    'A relative clause can sometimes shrink to a participle phrase when the meaning stays clear.',
    'The students who are waiting outside can board. The students waiting outside can board.',
    'Who are waiting shrinks to waiting.',
    'The students are waiting outside can board.',
    'The relative pronoun is gone, but the finite verb are is still there, so the clauses collide.',
    [Q('“The bus that is parked outside” can become…', 'the bus parked outside', 'the bus is parked outside as one noun phrase', 'parked the bus which', 'the that bus', 0, 'That is drops out and the participle remains.'), Q('Reduction works when the meaning…', 'stays the same', 'gains a new subject', 'loses the noun', 'becomes a question', 0, 'Waiting outside still identifies the students.'), Q('Which reduction is safe?', 'people living nearby', 'people are living nearby can vote, with no who', 'living people are nearby can', 'who people living', 0, 'Living nearby replaces who live nearby.'), Q('A reduced clause often starts with…', 'a participle', 'a finite verb plus the subject again', 'an article only', 'a modal perfect', 0, 'Waiting, parked, chosen.')]),
  R('advanced', 'Sentence relationships', 'ADV-23', 'Adverbial clauses of time, reason, purpose, result, condition and contrast',
    'An adverbial clause tells when, why, for what purpose, with what result, under what condition, or in spite of what.',
    'We left when the rain stopped, although we were still tired, so that we would catch the bus.',
    'When marks time, although marks contrast, and so that marks purpose.',
    'We left when. Although tired so that.',
    'The joining words have no clauses attached.',
    [Q('Because introduces…', 'a reason', 'a time only', 'a contrast only', 'a command', 0, 'We walked because the bus had left.'), Q('So that introduces…', 'a purpose', 'a finished fact with no aim', 'a noun', 'a plural', 0, 'We ran so that we would catch it.'), Q('Although introduces…', 'contrast', 'a timetable', 'possession', 'a question', 0, 'Although we were tired, we left.'), Q('If introduces…', 'a condition', 'a result by itself', 'an appositive', 'a reflexive', 0, 'If the bus is late, we walk.')]),
  R('advanced', 'Sentence relationships', 'ADV-24', 'Ellipsis and substitution',
    'Ellipsis leaves out words that the reader can restore. Substitution uses a short word such as do or one in their place.',
    'Maya caught the early bus, and Priya did too. I wanted a window seat and she wanted one too.',
    'Did stands in for caught the early bus. One stands in for a window seat.',
    'Maya caught the early bus, and Priya caught. I wanted a window seat and she wanted a too.',
    'The repeated words are cut without a substitute, so the second clause is unfinished.',
    [Q('In “Priya did too,” did substitutes for…', 'the verb phrase already used', 'a new noun', 'a comma', 'the subject Priya', 0, 'Did means caught the early bus.'), Q('One in “she wanted one too” replaces…', 'a window seat', 'wanted', 'she', 'too', 0, 'One is the substitute noun.'), Q('Ellipsis is safe when…', 'the missing words are obvious', 'the reader must guess the subject', 'the verb is new information', 'no earlier clause exists', 0, 'I can go if you can. Can implies can go.'), Q('Which line substitutes cleanly?', 'She left early, and I did too.', 'She left early, and I did the bus a new object.', 'She left, and I.', 'Did too she left nothing before.', 0, 'Did recovers left early.')]),
  R('advanced', 'Sentence relationships', 'ADV-25', 'Appositives',
    'An appositive is a noun phrase that renames the noun beside it. Extra appositives take commas.',
    'Priya, my cousin, saved the seat.',
    'My cousin renames Priya and is extra, so the commas belong.',
    'Priya my cousin saved the seat when the renaming is extra news.',
    'The commas that mark the extra name are missing.',
    [Q('An appositive…', 'renames a noun', 'is always a verb', 'asks a question', 'is a tense', 0, 'My cousin renames Priya.'), Q('An extra appositive is set off with…', 'commas', 'question marks', 'no punctuation, so it looks essential', 'a modal', 0, 'Priya, my cousin, saved the seat.'), Q('Removing “my cousin” from that sentence…', 'leaves a complete sentence', 'removes the verb', 'changes who saved it', 'makes Priya plural', 0, 'Priya saved the seat still works.'), Q('Which line contains an appositive?', 'The bus, a night service, left at 11.', 'The bus left at 11.', 'Left at 11 the.', 'A night left bus.', 0, 'A night service renames the bus.')]),
  R('advanced', 'Sentence relationships', 'ADV-26', 'Sentence connectors and transition words',
    'A connector such as however, therefore, or meanwhile shows how the new sentence relates to the one before it.',
    'The bus was late. Therefore we walked.',
    'Therefore tells the reader the walking is a result.',
    'The bus was late, therefore we walked.',
    'Therefore is a connector, not a joining word that can glue two full sentences with only a comma.',
    [Q('Therefore signals…', 'a result', 'a contrast', 'a time of day only', 'possession', 0, 'The lateness leads to the walk.'), Q('However signals…', 'contrast', 'a result you must accept', 'a plural', 'a command', 0, 'The bus was late. However, we still made it.'), Q('A connector between two full sentences usually needs…', 'a full stop or a semicolon before it', 'only a comma, as if it were and', 'no punctuation', 'a question mark', 0, 'The bus was late; therefore, we walked.'), Q('Meanwhile marks…', 'the same time', 'a cause', 'a possessive', 'an article', 0, 'We waited. Meanwhile, the rain stopped.')]),
  R('advanced', 'Sentence relationships', 'ADV-27', 'Correlative conjunctions: either…or, neither…nor, etc.',
    'Correlative conjunctions work in pairs. The grammar after each half should match.',
    'Either we catch this bus or we walk. Neither Maya nor Priya was late.',
    'Either…or offers two choices. Neither…nor excludes both, and the verb agrees with Priya, the nearer subject.',
    'Either we catch this bus or walking. Neither Maya or Priya were late.',
    'The second half does not match the first, and or is paired with neither.',
    [Q('The partner of either is…', 'or', 'nor', 'and', 'but', 0, 'Either…or.'), Q('The partner of neither is…', 'nor', 'or', 'and', 'so', 0, 'Neither…nor.'), Q('The two halves should be…', 'the same kind of structure', 'a noun and then a full story with no match', 'a question and a comma', 'different tenses on purpose', 0, 'We catch this bus matches we walk.'), Q('With neither…nor, the verb often agrees with…', 'the subject nearer the verb', 'the subject farther away always', 'neither itself as a plural', 'the first noun only', 0, 'Neither Maya nor Priya was late.')]),
  R('advanced', 'Sentence relationships', 'ADV-28', 'Parallelism with paired structures',
    'With both…and, either…or, and not only…but also, the words after each piece should share a shape.',
    'She not only missed the bus but also left her pass.',
    'Missed and left are both verbs.',
    'She not only missed the bus but also her pass was left behind in a different shape.',
    'The second half switches from a verb to a new clause.',
    [Q('Parallel paired structures need…', 'the same shape after each piece', 'a longer second half no matter the grammar', 'a comma only', 'two subjects always', 0, 'Not only missed… but also left…'), Q('Which line is parallel?', 'both tired and late', 'both tired and she was late', 'either walking or we walk', 'not only the bus but also she left', 0, 'Tired and late are both adjectives.'), Q('Either…or should be followed by…', 'matching forms', 'a noun and then a paragraph', 'a question and a command', 'unrelated tenses', 0, 'Either a bus or a walk.'), Q('Fix the pair “not only late but also she missed it.”', 'not only late but also lost', 'not only was late but also the pass', 'late not only missed', 'but also not only', 0, 'Late and lost can both describe her result. Matching adjectives or matching verbs keep the pair parallel.')]),
  R('advanced', 'Meaning and communication (nuanced)', 'ADV-29', 'Expressing cause, purpose, result and contrast',
    'Because, so that, so, and although each name a different relationship.',
    'Because the bus was late, we ran so that we would arrive, although we were tired.',
    'Because gives the cause, so that gives the purpose, and although gives the contrast.',
    'Although the bus was late, we ran because we would arrive, so that we were tired.',
    'The relationship words point at the wrong ideas.',
    [Q('A cause is marked by…', 'because', 'so that', 'although', 'meanwhile as a cause', 0, 'Because the bus was late.'), Q('A purpose is marked by…', 'so that', 'because', 'however', 'too', 0, 'So that we would arrive.'), Q('A contrast is marked by…', 'although', 'because', 'so', 'therefore only', 0, 'Although we were tired.'), Q('So between two clauses often marks…', 'a result', 'a person', 'a possessive', 'a relative', 0, 'The bus was late, so we walked.')]),
  R('advanced', 'Meaning and communication (nuanced)', 'ADV-30', 'Formal versus conversational constructions',
    'The same meaning can be built in a formal shape or a conversational one.',
    'I am writing to explain the delay. Just wanted to say the bus was late.',
    'The first fits a teacher. The second fits a friend.',
    'I am writing to explain the delay lol. Just wanted to say the bus was late, Dear Sir.',
    'The construction and the audience do not match.',
    [Q('A formal explanation can begin…', 'I am writing to explain…', 'Gonna explain real quick…', 'u there', 'lol so', 0, 'I am writing to is a formal opener.'), Q('A conversational version may use…', 'short forms and a direct tone', 'Dear Sir or Madam in a text to a friend', 'no verb on purpose', 'passive voice in every chat', 0, 'Just wanted to say is conversational.'), Q('The construction should follow…', 'the audience', 'the longest possible sentence', 'a single style for every room', 'the spelling of bus', 0, 'A teacher and a friend do not need the same shape.'), Q('Which line is conversational?', 'The bus was late, so I walked.', 'I wish to inform you of a delay to my arrival.', 'Please accept this account of events.', 'I am writing with regard to the timetable.', 0, 'The short cause-and-result line sounds like speech.')]),
  R('advanced', 'Meaning and communication (nuanced)', 'ADV-31', 'Register, audience and tone',
    'Register is the level of language. Audience is who will read or hear it. Tone is the attitude that comes through.',
    'Sorry I missed the start. The bus did not come, so I walked.',
    'That is respectful, specific, and aimed at a teacher.',
    'Yo, bus ghosted me, not my fault.',
    'The tone blames and the register is too casual for a teacher.',
    [Q('Register means…', 'how formal or casual the language is', 'the bus route number', 'the tense only', 'the page count', 0, 'Sorry I missed the start is a different register from yo.'), Q('Audience means…', 'the people who will receive the message', 'the writer only', 'the verb', 'the comma', 0, 'A teacher and a friend are different audiences.'), Q('Tone is…', 'the attitude in the wording', 'the font', 'the subject only', 'a prefix', 0, 'Not my fault sounds defensive.'), Q('Which tone fits an apology to a teacher?', 'Sorry I missed the start. I walked.', 'Whatever, I was late.', 'Not my problem.', 'Bus ghosted me.', 0, 'It takes responsibility and stays respectful.')]),
  R('advanced', 'Meaning and communication (nuanced)', 'ADV-32', 'Hedging: perhaps, may, tends to, etc.',
    'A hedge softens a claim when you are not fully certain or when a hard claim would sound too strong.',
    'The bus tends to be late on Fridays. She may have missed it.',
    'Tends to avoids always. May have leaves the past possible rather than certain.',
    'The bus is always late on Fridays, I know it, and she definitely missed it, when you only have a pattern and a guess.',
    'The wording is more certain than the evidence.',
    [Q('A hedge is useful when…', 'you are not fully sure', 'you saw the event yourself and need a fact', 'you are giving a command', 'you are naming a person', 0, 'May and perhaps leave room.'), Q('Tends to means…', 'usually, not always', 'never', 'must', 'a finished single event', 0, 'The bus tends to be late.'), Q('“She may have missed it” is…', 'a cautious past possibility', 'a proven fact', 'a command', 'a plural noun', 0, 'May have hedges the conclusion.'), Q('Which claim is hedged?', 'It is possible the stop clock is wrong.', 'The stop clock is wrong. I am certain.', 'The clock broke. I watched it.', 'Wrong clock, full stop, no doubt.', 0, 'It is possible softens the claim.')]),
  R('advanced', 'Meaning and communication (nuanced)', 'ADV-33', 'Cohesion and reference across sentences',
    'Cohesion is how sentences hold together. Pronouns, repeated nouns, and connectors point back so the reader can follow.',
    'Maya missed the bus. She then texted Priya, who was already on it.',
    'She points to Maya. Who points to Priya. It points to the bus.',
    'Maya missed the bus. She then texted her, who was already on it, when both people could be she or her.',
    'The pronouns do not tell the reader which person is meant.',
    [Q('Cohesion is…', 'the links between sentences', 'a single spelling rule', 'a tense name', 'an article', 0, 'Pronouns and connectors make those links.'), Q('In the clear pair, she refers to…', 'Maya', 'Priya', 'the bus', 'the text', 0, 'Maya is the earlier named person who missed the bus.'), Q('An unclear pronoun…', 'could point to more than one noun', 'always points to the subject', 'is more precise', 'replaces cohesion on purpose', 0, 'She texted her leaves both people possible.'), Q('A connector such as then…', 'shows the next step', 'renames Maya', 'is a possessive', 'starts a new topic with no link', 0, 'Then ties the text to the missed bus.')]),
  R('advanced', 'Advanced accuracy', 'ADV-34', 'Common prepositional combinations',
    'Many adjectives, verbs, and nouns take one preposition and sound wrong with another.',
    'She is good at maths. We arrived at the stop. He apologised for the delay.',
    'Good takes at. Arrive takes at for a point. Apologise takes for.',
    'She is good in maths in this usual pair. We arrived to the stop. He apologised the delay.',
    'The prepositions are not the ones these words partner with.',
    [Q('Good in “good ___ maths” takes…', 'at', 'in', 'on', 'for', 0, 'Good at maths.'), Q('Apologise takes…', 'for', 'to the thing you did, with no for', 'at a fault', 'on a delay', 0, 'Apologise for the delay. Apologise to a person.'), Q('Arrive at a building or stop uses…', 'at', 'to', 'in a point you reach', 'on', 0, 'We arrived at the stop.'), Q('Which line uses the usual preposition?', 'interested in the result', 'interested on the result', 'interested at the result', 'interested for the result', 0, 'Interested in is the combination.')]),
  R('advanced', 'Advanced accuracy', 'ADV-35', 'Verb patterns and complementation',
    'The complement is the pattern a verb requires: a gerund, an infinitive, a that-clause, or an object plus a form.',
    'She suggested leaving. She suggested that we leave. She wanted us to leave.',
    'Suggest takes a gerund or a that-clause. Want takes an object plus to.',
    'She suggested to leave. She wanted that we leave as the usual pattern. She suggested us leaving as the main pattern.',
    'Suggest is given want’s infinitive, and want is given suggest’s that-clause.',
    [Q('Suggest is commonly followed by…', 'a gerund or a that-clause', 'to plus the base verb', 'an object plus a base verb with no to', 'a possessive only', 0, 'She suggested leaving. She suggested that we leave.'), Q('Want someone to do it uses…', 'an object plus to plus the verb', 'a that-clause in the usual pattern', 'a gerund only', 'a modal perfect', 0, 'She wanted us to leave.'), Q('Enjoy takes…', 'a gerund', 'an infinitive', 'a that-clause as its main pattern', 'a base verb', 0, 'She enjoys walking.'), Q('Which pattern fits recommend?', 'I recommend waiting.', 'I recommend to wait.', 'I recommend us wait.', 'Recommend waiting I to.', 0, 'Recommend takes the gerund.')]),
  R('advanced', 'Advanced accuracy', 'ADV-36', 'Phrasal-prepositional verbs',
    'A phrasal-prepositional verb has a particle and a preposition, and the object comes after both.',
    'We ran out of time. She looks forward to the trip. I will catch up with you.',
    'Out of, forward to, and up with are fixed. The object follows the whole combination.',
    'We ran out time. She looks forward the trip. I will catch up you.',
    'The preposition in the combination is missing.',
    [Q('Run out of means…', 'have no more of something', 'exit a building only', 'postpone', 'search a list', 0, 'We ran out of time.'), Q('The object of look forward to comes…', 'after to', 'between look and forward', 'before look', 'nowhere', 0, 'Look forward to the trip.'), Q('Catch up with is…', 'a verb plus a particle plus a preposition', 'a single-word verb', 'an article', 'a tense', 0, 'Up is the particle and with is the preposition.'), Q('Which line keeps the whole combination?', 'She gets on with her partner.', 'She gets on her partner.', 'She gets with on her partner.', 'Gets she on.', 0, 'Get on with needs both on and with.')]),
  R('advanced', 'Advanced accuracy', 'ADV-37', 'Reduced clauses',
    'A reduced clause drops a subject and a form of be, or a relative pronoun, when the reader can still see who does the action.',
    'While waiting for the bus, Maya checked the time. The pass left on the seat was hers.',
    'While she was waiting shrinks because Maya is the one waiting. Left on the seat shrinks that was left.',
    'While waiting for the bus, the time was checked, if Maya is the one waiting.',
    'The reduced clause is attached to the wrong noun.',
    [Q('A reduced clause must still make clear…', 'who or what the phrase describes', 'a new unrelated subject', 'a second tense', 'a question', 0, 'While waiting describes Maya.'), Q('“The pass left on the seat” comes from…', 'the pass that was left on the seat', 'the pass left the seat as an action', 'left is the main finite verb of a new clause', 'a command', 0, 'That was drops out.'), Q('Which reduction is attached well?', 'After missing the bus, we walked.', 'After missing the bus, the walk started.', 'Waiting at the stop, a delay happened to us as the waiters.', 'Left on the seat, Maya was a pass.', 0, 'We are the people who missed the bus.'), Q('While waiting is reduced from…', 'while she was waiting', 'wait', 'a noun', 'although', 0, 'The subject and was are restored from the main clause.')]),
  R('advanced', 'Advanced accuracy', 'ADV-38', 'Cleft sentences for emphasis',
    'A cleft sentence splits one idea so that one piece is spotlighted.',
    'It was Maya who sent the file. What we need is a later bus.',
    'It was… who spotlights Maya. What we need spotlights a later bus.',
    'Maya sent the file, with no extra focus, when the point is to stress Maya. It was Maya which sent the file.',
    'The plain sentence does not spotlight anyone, and which is the wrong pronoun for a person.',
    [Q('“It was Maya who sent the file” emphasises…', 'Maya', 'the file more than Maya', 'sent', 'a time', 0, 'The it-cleft puts Maya in the frame.'), Q('A person in an it-cleft takes…', 'who', 'which', 'where', 'what as the person', 0, 'It was Maya who, not which.'), Q('“What we need is a later bus” spotlights…', 'a later bus', 'we', 'need as a noun', 'is', 0, 'The what-cleft frames the thing needed.'), Q('Which line is a cleft?', 'It was the late bus that made us walk.', 'The late bus made us walk.', 'We walked.', 'A bus.', 0, 'It was… that splits out the late bus.')]),
  R('advanced', 'Advanced accuracy', 'ADV-39', 'Inversion after negative expressions',
    'When a negative or near-negative expression opens the sentence, the helping verb comes before the subject.',
    'Not until 8 did the bus arrive. Under no circumstances should you leave your pass.',
    'Did and should move in front of the subject because the negative phrase is first.',
    'Not until 8 the bus arrived. Under no circumstances you should leave your pass.',
    'The negative phrase is first, but the helping verb has not moved.',
    [Q('Not until 8 ___ the bus arrive.', 'did', 'the bus did before arrive', 'arrived with no helping verb', 'does after the subject', 0, 'Did comes before the bus.'), Q('Under no circumstances ___ you leave.', 'should', 'you should', 'leave you', 'should to', 0, 'The modal comes before the subject.'), Q('This inversion happens because…', 'a negative expression is in front', 'the sentence is a normal statement', 'the noun is plural', 'there is a comma', 0, 'The fronted negative triggers the flip.'), Q('Which line inverts correctly?', 'Rarely have we been this late.', 'Rarely we have been this late.', 'Never we have seen it.', 'Little she did know.', 0, 'Have comes before we.')]),
  R('advanced', 'Advanced accuracy', 'ADV-40', 'Conditionals: zero, first, second, third and mixed',
    'The tense in an if-sentence shows whether the result is always true, likely, unreal now, unreal in the past, or mixed across times.',
    'If you heat water, it boils. If I had set an alarm, I would not be late now.',
    'The first is a zero conditional, always true. The second is mixed: a past cause with a present result.',
    'If you will heat water, it boiled. If I set an alarm yesterday, I am not late now as the unreal past.',
    'The verb forms do not match a conditional type.',
    [Q('“If you heat water, it boils” is…', 'zero', 'third', 'mixed', 'a command', 0, 'Both halves are present because the result always follows.'), Q('A real future possibility is…', 'If it rains, we will walk.', 'If it rained yesterday, we walk.', 'If it had rained, we walked as a fact.', 'Rains if will.', 0, 'Present in the if-clause and will in the result is the first conditional.'), Q('An unreal past is…', 'If I had left earlier, I would have caught it.', 'If I leave earlier, I caught it.', 'If I had left, I catch it.', 'Had leave if.', 0, 'Had left and would have caught are both past and unreal.'), Q('“If I had set an alarm, I would not be late now” mixes…', 'a past cause and a present result', 'two present facts', 'a command and a noun', 'two articles', 0, 'Had set is past. Would not be is present.')]),
  R('advanced', 'Advanced accuracy', 'ADV-41', 'Wishes, regrets and hypothetical situations',
    'Wish and if only shift the tense back to show that the situation is not real.',
    'I wish I knew the answer. If only I had left earlier.',
    'Knew is present unreal. Had left is a past regret.',
    'I wish I know the answer. If only I left earlier yesterday as the regret form.',
    'The tense has not shifted, so the wish sounds like a fact.',
    [Q('A wish about now uses…', 'a past form', 'a present form', 'a future will', 'an -s verb', 0, 'I wish I knew, not I wish I know.'), Q('A regret about the past uses…', 'had plus the past participle', 'the present simple', 'will', 'a gerund only', 0, 'If only I had left earlier.'), Q('“I wish I were taller” uses were because…', 'the wish is unreal', 'it is a fact', 'were is only for crowds', 'wish is an adjective', 0, 'Were marks the unreal present.'), Q('Which line is a past regret?', 'She wishes she had texted.', 'She wishes she texts.', 'She wishes she will text.', 'Wish she texted now as a finished regret only.', 0, 'Had texted places the regret in the past.')]),
  R('advanced', 'Advanced accuracy', 'ADV-42', 'Advanced passive constructions',
    'The passive can be built with modals, perfect forms, and reporting verbs when the receiver of the action matters more than the doer.',
    'The file should have been sent. It is thought that the bus left early. She was made to wait.',
    'Should have been sent is a modal perfect passive. Is thought reports a view. Was made to wait keeps to in this passive.',
    'The file should have sent. It thinks that the bus left. She was made wait.',
    'The passive auxiliaries and the to after made are missing.',
    [Q('A modal perfect passive looks like…', 'should have been sent', 'should have sent', 'should sent been', 'been should sent', 0, 'Modal plus have been plus the past participle.'), Q('“It is thought that…” …', 'reports a general view', 'names the thinker as the subject', 'is a command', 'is active with a person', 0, 'The thinker is left unstated.'), Q('The passive of “They made her wait” is…', 'She was made to wait.', 'She was made wait.', 'She made was to wait.', 'Wait was she made.', 0, 'Make loses its bare infinitive and takes to in the passive.'), Q('Which line is passive?', 'The seats are being saved.', 'We are saving the seats.', 'Save the seats.', 'We saved them.', 0, 'Are being saved puts the seats first.')]),
  R('advanced', 'Advanced accuracy', 'ADV-43', 'Reported speech with tense, time and place changes',
    'When you report speech later or from somewhere else, tense, time words, and place words often shift.',
    '“I will finish this here today,” she said. She said she would finish that there that day.',
    'Will becomes would, this becomes that, here becomes there, and today becomes that day.',
    'She said she will finish this here today, spoken the next day from another room.',
    'The time and place words still belong to the original moment.',
    [Q('Will in a later report often becomes…', 'would', 'will, unchanged, after a past reporting verb', 'willed', 'a noun', 0, 'She said she would finish.'), Q('Today, reported the next day, often becomes…', 'that day', 'today', 'yesterday as the same day', 'now', 0, 'The day has moved.'), Q('Here, reported from somewhere else, often becomes…', 'there', 'here', 'this', 'where never', 0, 'The place is no longer the speaker’s here.'), Q('“I did it yesterday,” said on Monday about Sunday, and reported on Tuesday, can become…', 'She said she had done it the day before.', 'She said she did it yesterday, meaning Monday.', 'She said I did it yesterday.', 'Said she yesterday did.', 0, 'The tense steps back and yesterday becomes the day before.')]),
  R('advanced', 'Advanced accuracy', 'ADV-44', 'Ambiguity and unclear references',
    'A sentence is ambiguous when a phrase or a pronoun can attach to more than one word.',
    'Maya told Priya that she had missed the bus, and Maya was the one who missed it.',
    'Naming Maya again removes the doubt about she.',
    'Maya told Priya that she had missed the bus.',
    'She could be Maya or Priya.',
    [Q('An ambiguous pronoun…', 'can point to more than one noun', 'has one possible meaning', 'is always herself', 'is a connector', 0, 'She could be either person.'), Q('A clearer version…', 'repeats the name or rebuilds the sentence', 'adds another she', 'deletes the verb', 'uses only pronouns', 0, 'Maya was the one who missed it.'), Q('“I saw the student with the phone” can mean…', 'the student had the phone, or I used the phone to see them', 'only one meaning', 'a tense change', 'a plural verb', 0, 'With the phone can attach in two places.'), Q('Which line is unambiguous?', 'Priya missed the bus, and Maya told her.', 'She told her that she missed it.', 'The student with the binoculars saw the student with the phone, and with could be either.', 'He asked him if he knew.', 0, 'The names and her line up in one direction.')]),
  R('advanced', 'Advanced accuracy', 'ADV-45', 'British and American grammar differences',
    'Both varieties are standard. A piece of writing should stay with one variety’s forms.',
    'British: The team are ready. She has got a pass. American: The team is ready. She has a pass.',
    'The collective verb and have got versus have are familiar differences. Each line is consistent inside its variety.',
    'The team are ready and she has gotten a pass in the same formal paragraph that also says whilst and toward without choosing a variety.',
    'British and American forms are mixed in one passage.',
    [Q('A collective noun as a unit is often singular in…', 'American English', 'neither variety', 'only headlines', 'questions', 0, 'The team is ready is the usual American choice.'), Q('Have got for possession is common in…', 'British English', 'neither standard variety', 'past perfect only', 'commands', 0, 'She has got a pass.'), Q('A single piece of writing should…', 'stay with one variety', 'switch forms every sentence', 'avoid both', 'use only slang', 0, 'Mixing whilst and gotten in one paragraph looks unsettled.'), Q('Which pair is internally consistent?', 'The team is ready. She has a pass.', 'The team are ready. She has gotten a pass. Whilst we traveled toward…', 'Have got and gotten in one formal note.', 'Whilst the team is, gotten.', 0, 'Both choices match one common American pattern.')]),
];
